### ISSUE TITLE
modifyCacheKey() uses the wrong language to find the rootPage

### ISSUE THREAD

**Issue by davidmaack** [codefog/contao-cookiebar#11]
When the page is cached, no rootPageId is given. But using \PageModel::findFirstPublishedRootByHostAndLanguage() might fetch the wrong root page, depending on the language settings of the browser.

At this point TL_LANGUAGE is set to the preferred browser language, which might not be the language of the correct root page. So the function will return the wrong page.

A possible solution would be to store the root page in in the cache as well, e.g using the request as a key in getCurrentRootPage() instead of the rootId.

**Comment by qzminski** [comment]
I don't think using request as a cache key to fetch rootId is a good idea. What if the user changes the domain name in the website root settings?

**Comment by davidmaack** [comment]
Ok, use \Environment::get('requestUri') then, there is no domain involved here.

Any other ideas for a good key? It must be available when the page is served from cache...

**Comment by qzminski** [comment]
My previous comment was quite irrelevant because the host and request is already a part of the cache key:

https://github.com/contao/core/blob/master/system/modules/core/controllers/FrontendIndex.php#L357

The cache works the way that it gets the current request as string and checks if cache file for it already exists. So to get the correct website root, I would need to parse the URL anyway. Do you think the below method would be relevant for getting the current root page? Can you try it out in your environment?

https://github.com/contao/core/blob/master/system/modules/core/classes/Frontend.php#L294
