### ISSUE TITLE
Cookiebar with Live Helper Chat

### ISSUE THREAD

**Issue by Waldknoblauch** [codefog/contao-cookiebar#5]
Hello, we use cookiebar along with Live helper chat: www.livehelperchat.com

Cookiebar does not work properly here. The display "top" does not work, and display "bottom" appear again an again ... (On the main page)

Thank you!

www.reibener-hof.de

**Comment by qzminski** [comment]
The display "top" does work, it's just your website styles that hide it - or actually the top bar overlaps it. Try setting the higher ```z-index``` value of the ```#cookiebar``` and it should appear again.

I just clicked on the ```Akzeptieren``` button and bar was hidden. It won't display anymore for me because of the cookies, so it seems to work correctly.
