### ISSUE TITLE
Real Opt-In for tracking code and other scripts

### ISSUE THREAD

**Issue by birdmedia** [codefog/contao-cookiebar#62]
The current version of cookiebar just displays a message and enables opt-out for Google Analytics. It would be nice, if there would be a real opt-in to publish certain lines of code only if the user agrees to the terms and conditions. Like insert field_x in header or footer when COOKIEBAR_X is set and reload the page.

**Comment by qzminski** [comment]
Inserting field value into the page would still have to be a JS solution as otherwise it would interfere with Contao page cache. The checkbox is only a simple local storage flag switcher and is not designed to be anything else than that. 

As stated in the documentation, how you handle the analytics is an individual case and cookiebar will not provide any _default_ solutions of out the box. For your case a page reload would be fine, but someone would maybe want to use a function that can be executed without leaving the page. In my opinion this is too specific to be a part of the extension.
