### ISSUE TITLE
field length too short

### ISSUE THREAD

**Issue by eBlick** [codefog/contao-cookiebar#9]
THX for this extension.
I find the text-length too short and have changed the 

'exclude'                 => true,
	'inputType'               => 'text',
	'eval'                    => array('mandatory'=>true, 'tl_class'=>'clr long'),
	'sql'                     => "varchar(255) NOT NULL default ''"

into 

'inputType'               => 'textarea',
	'search'                  => true,
	'eval'                    => array('rte'=>'tinyMCE', 'tl_class'=>'clr'),
	'sql'                     => "text NULL"

This might be interesting for other users and perhaps you could change it with the next update.

**Comment by qzminski** [comment]
I have extended the message field length in 6ebb896. However the rich text editor was not introduced because the cookiebar is meant to display only a short and plain text message about the cookie information. The cookie policy details should be placed on an individual page where you can have any formatting you wish.
